---
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    environment:
      - TZ=America/Costa_Rica
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/storage/Media/Movies:/Films:ro
      - /mnt/storage/Media/TVShows:/TVShows:ro
      - /mnt/storage/Media/Audiobooks:/Audiobooks:ro
      #- /mnt/storage/Media/Music:/Music:ro
    #devices: uncomment these and amend if you require GPU accelerated transcoding
    #  - /dev/dri/renderD128:/dev/dri/renderD128
    #  - /dev/dri/card0:/dev/dri/card0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${APP_DOMAIN}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  proxy:
    external: true
