---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
	restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.${APP_DOMAIN} #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /path/to/appdata/config:/config
	networks:
		proxy
	labels:
	  - "traefik.enable=true"
	  - "traefik.http.routers.code-server.entrypoints=http"
	  - "traefik.http.routers.code-server.rule=Host(`code-server.${APP_DOMAIN}`)"
	  - "traefik.http.middlawares.code-server-https-redirect.redirectscheme.scheme=https"
	  - "traefik.http.routers.code-server.middlawares=code-server-https-redirect"
	  - "traefik.http.routers.code-server-secure.entrypoints=https"
	  - "traefik.http.routers.code-server-secure.rule=Host(`code-server.${APP_DOMAIN}`)"
	  - "traefik.http.routers.code-server-secure.tls=true"
	  - "traefik.http.routers.code-server-secure.service=code-server"
	  - "traefik.http.routers.code-server.loadbalancer.server.port=8443"
	  - "traefik.docker.network=proxy"
	
networks:
	proxy:
		external: true