---
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - WG_HOST=wireguard.${APP_DOMAIN}
      - PASSWORD=${PASSWORD}
    volumes:
      - wireguard:/etc/wireguard
    networks:
      proxy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=http"
      - "traefik.http.routers.vaultwarden.rule=Host(`wireguard.${APP_DOMAIN}`)"
      - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect"
      - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`wireguard.${APP_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden-secure.tls=true"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=51820"
      - "traefik.docker.network=proxy"
volumes:
  wireguard:
      
networks:
  proxy:
    external: true
