---
services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.it-tools-secure.tls=true"
      - "traefik.http.routers.it-tools-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.it-tools-secure.service=it-tools"
      - "traefik.http.routers.it-tools-secure.entrypoints=https"
      - "traefik.http.routers.it-tools-secure.rule=Host(`tools.${APP_DOMAIN}`)"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
