---
services:
  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - docuseal:/data/docuseal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.docuseal-secure.tls=true"
      - "traefik.http.routers.docuseal-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.docuseal-secure.service=docuseal"
      - "traefik.http.routers.docuseal-secure.entrypoints=https"
      - "traefik.http.routers.docuseal-secure.rule=Host(`docuseal.${APP_DOMAIN}`)"
      - "traefik.http.services.docuseal.loadbalancer.server.port=3000"

volumes:
  docuseal:

networks:
  proxy:
    external: true
