---
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
      - TZ=Etc/UCT
    security_opt:
      - no-new-privileges:true
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql/
      
volumes:
  sql-server-data:
