---
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - vaultwarden:/data/
    networks:
      - proxy_external
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_external"
      - "traefik.http.routers.vaultwarden-secure.tls=true"
      - "traefik.http.routers.vaultwarden-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
      - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`vaultwarden.${APP_DOMAIN}`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

volumes:
  vaultwarden:

networks:
  proxy_external:
    external: true
